# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake CI

on:
  push:
    branches: [ "dev", "feature/**"]
  pull_request:
    branches: [ "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential cmake
    
    - name: Configure CMake
      run: cmake -B build
    
    - name: Build
      run: cmake --build build -- -j2
    
    - name: Test
      working-directory: build
      run: ctest -j2